// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user/user.proto

/*
Package go_micro_srv_user is a generated protocol buffer package.

It is generated from these files:
	proto/user/user.proto

It has these top-level messages:
	User
	GetRequest
	Response
*/
package go_micro_srv_user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Id       string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	DeviceId string `protobuf:"bytes,2,opt,name=device_id,json=deviceId" json:"device_id,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

type GetRequest struct {
}

func (m *GetRequest) Reset()                    { *m = GetRequest{} }
func (m *GetRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()               {}
func (*GetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Response struct {
	Created bool    `protobuf:"varint,1,opt,name=created" json:"created,omitempty"`
	User    *User   `protobuf:"bytes,2,opt,name=user" json:"user,omitempty"`
	Users   []*User `protobuf:"bytes,3,rep,name=users" json:"users,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Response) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *Response) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Response) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "go.micro.srv.user.User")
	proto.RegisterType((*GetRequest)(nil), "go.micro.srv.user.GetRequest")
	proto.RegisterType((*Response)(nil), "go.micro.srv.user.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for UserService service

type UserServiceClient interface {
	CreateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*Response, error)
	GetUsers(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Response, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) CreateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/go.micro.srv.user.UserService/CreateUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUsers(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/go.micro.srv.user.UserService/GetUsers", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceServer interface {
	CreateUser(context.Context, *User) (*Response, error)
	GetUsers(context.Context, *GetRequest) (*Response, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.micro.srv.user.UserService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.micro.srv.user.UserService/GetUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUsers(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "go.micro.srv.user.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _UserService_CreateUser_Handler,
		},
		{
			MethodName: "GetUsers",
			Handler:    _UserService_GetUsers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/user/user.proto",
}

func init() { proto.RegisterFile("proto/user/user.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0xcd, 0xb6, 0x6a, 0x3a, 0x15, 0xc1, 0x01, 0x31, 0x58, 0x84, 0x92, 0x93, 0x20, 0x46,
	0x68, 0x1f, 0x41, 0xa1, 0x7a, 0x8d, 0x78, 0x16, 0xdd, 0x0c, 0x92, 0x83, 0xa6, 0x66, 0xd2, 0x9e,
	0x7d, 0x11, 0xdf, 0x55, 0x32, 0xcb, 0xe2, 0xc1, 0x55, 0x2f, 0xbb, 0xfc, 0x33, 0x5f, 0xfe, 0xf9,
	0x67, 0xe0, 0x78, 0x9d, 0x53, 0x49, 0x57, 0x1b, 0xa6, 0x2c, 0x1f, 0x27, 0x1a, 0x8f, 0x5e, 0x92,
	0x7b, 0x8d, 0x6d, 0x4e, 0x8e, 0xf3, 0xd6, 0xd5, 0x86, 0x5d, 0xc2, 0xf8, 0x81, 0x29, 0xe3, 0x21,
	0x34, 0x31, 0x18, 0x35, 0x57, 0xe7, 0x13, 0xdf, 0xc4, 0x80, 0x33, 0x98, 0x04, 0xda, 0xc6, 0x96,
	0x1e, 0x63, 0x30, 0x8d, 0x94, 0x75, 0x57, 0xb8, 0x0b, 0xf6, 0x00, 0x60, 0x45, 0xc5, 0xd3, 0xfb,
	0x86, 0xb8, 0xd8, 0x0f, 0x05, 0xda, 0x13, 0xaf, 0xd3, 0x1b, 0x13, 0x1a, 0xd8, 0x6f, 0x33, 0x3d,
	0x15, 0xea, 0xcc, 0xb4, 0xef, 0x25, 0x5e, 0xc0, 0xb8, 0x4e, 0x14, 0xb3, 0xe9, 0xe2, 0xc4, 0xfd,
	0xc8, 0xe2, 0x6a, 0x10, 0x2f, 0x10, 0x5e, 0xc2, 0x6e, 0xfd, 0xb3, 0x19, 0xcd, 0x47, 0x7f, 0xd1,
	0x1d, 0xb5, 0xf8, 0x54, 0x30, 0xad, 0xfa, 0x9e, 0x72, 0x8d, 0x88, 0x37, 0x00, 0xd7, 0x32, 0x56,
	0x76, 0xfb, 0xed, 0xf5, 0xe9, 0x6c, 0xa0, 0xd1, 0x6f, 0x62, 0x77, 0xf0, 0x16, 0xf4, 0x8a, 0x4a,
	0x25, 0x19, 0xcf, 0x06, 0xd0, 0xef, 0x1b, 0xfc, 0xe3, 0xf4, 0xbc, 0x27, 0xf7, 0x5f, 0x7e, 0x05,
	0x00, 0x00, 0xff, 0xff, 0xcc, 0xf5, 0xd1, 0x9e, 0x98, 0x01, 0x00, 0x00,
}
